import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:fake_cloud_firestore/fake_cloud_firestore.dart';
import 'package:farm_app/src/features/tasks/domain/task.dart';
import 'package:flutter_test/flutter_test.dart';

void main() {
  group('TaskType.fromString', () {
    test('resolves known values', () {
      expect(TaskType.fromString('pregnancy_check'), TaskType.pregnancyCheck);
      expect(TaskType.fromString('farrowing_prep'), TaskType.farrowingPrep);
      expect(
          TaskType.fromString('farrowing_expected'), TaskType.farrowingExpected);
      expect(TaskType.fromString('vaccination_due'), TaskType.vaccinationDue);
      expect(TaskType.fromString('withdrawal_end'), TaskType.withdrawalEnd);
      expect(TaskType.fromString('manual'), TaskType.manual);
    });

    test('defaults to manual on unknown value', () {
      expect(TaskType.fromString('unknown_value'), TaskType.manual);
    });
  });

  group('TaskStatus.fromString', () {
    test('resolves known values', () {
      expect(TaskStatus.fromString('open'), TaskStatus.open);
      expect(TaskStatus.fromString('completed'), TaskStatus.completed);
      expect(TaskStatus.fromString('skipped'), TaskStatus.skipped);
    });

    test('defaults to open on unknown value', () {
      expect(TaskStatus.fromString('???'), TaskStatus.open);
    });
  });

  test('FarmTask round-trips through Firestore', () async {
    final f = FakeFirebaseFirestore();
    final dueDate = Timestamp.fromMillisecondsSinceEpoch(1700000000000);
    final createdAt = Timestamp.fromMillisecondsSinceEpoch(1699000000000);
    final task = FarmTask(
      id: 't1',
      farmId: 'f1',
      type: TaskType.pregnancyCheck,
      title: 'Pregnancy check for SOW-001',
      description: 'verify pregnancy ultrasound',
      dueDate: dueDate,
      relatedPigId: 'sow1',
      relatedBreedingId: 'br1',
      relatedBatchId: null,
      relatedAreaId: 'a1',
      assignedTo: const TaskAssignment(kind: 'user', id: 'u1'),
      status: TaskStatus.open,
      autoGenerated: true,
      source: const TaskSource(collection: 'breeding_records', docId: 'br1'),
      completedBy: null,
      completedAt: null,
      createdAt: createdAt,
    );

    await f
        .collection('farms')
        .doc('f1')
        .collection('tasks')
        .doc('t1')
        .set(task.toMap());

    final doc = await f
        .collection('farms')
        .doc('f1')
        .collection('tasks')
        .doc('t1')
        .get();
    final hydrated = FarmTask.fromFirestore(doc, farmId: 'f1');

    expect(hydrated.id, 't1');
    expect(hydrated.farmId, 'f1');
    expect(hydrated.type, TaskType.pregnancyCheck);
    expect(hydrated.title, 'Pregnancy check for SOW-001');
    expect(hydrated.description, 'verify pregnancy ultrasound');
    expect(hydrated.dueDate, dueDate);
    expect(hydrated.relatedPigId, 'sow1');
    expect(hydrated.relatedBreedingId, 'br1');
    expect(hydrated.relatedBatchId, isNull);
    expect(hydrated.relatedAreaId, 'a1');
    expect(hydrated.assignedTo?.kind, 'user');
    expect(hydrated.assignedTo?.id, 'u1');
    expect(hydrated.status, TaskStatus.open);
    expect(hydrated.autoGenerated, isTrue);
    expect(hydrated.source?.collection, 'breeding_records');
    expect(hydrated.source?.docId, 'br1');
    expect(hydrated.createdAt, createdAt);
  });
}
