import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:fake_cloud_firestore/fake_cloud_firestore.dart';
import 'package:farm_app/src/features/tasks/application/task_generator.dart';
import 'package:farm_app/src/features/tasks/data/task_repository.dart';
import 'package:flutter_test/flutter_test.dart';

void main() {
  test(
      'breeding write generates pregnancy_check + farrowing_prep + farrowing_expected',
      () async {
    final f = FakeFirebaseFirestore();
    final tasks = TaskRepository(f);
    final gen = TaskGenerator(f, tasks);
    final batch = f.batch();
    final inseminationDate = Timestamp.fromMillisecondsSinceEpoch(1700000000000);

    gen.addBreedingTasksToBatch(
      batch: batch,
      farmId: 'f1',
      breedingRecordId: 'br1',
      sowId: 'sow1',
      sowTagId: 'SOW-001',
      areaId: 'a1',
      inseminationDate: inseminationDate,
    );
    await batch.commit();

    final snap =
        await f.collection('farms').doc('f1').collection('tasks').get();
    expect(snap.docs, hasLength(3));
    final types = snap.docs.map((d) => d.data()['type']).toSet();
    expect(types, {'pregnancy_check', 'farrowing_prep', 'farrowing_expected'});

    // Ensure idempotent task IDs follow the documented pattern.
    final ids = snap.docs.map((d) => d.id).toSet();
    expect(ids, {'br_br1_preg', 'br_br1_prep', 'br_br1_farr'});

    // Verify due dates are insemination + 30 / +107 / +114 days.
    final byId = {for (final d in snap.docs) d.id: d.data()};
    final ins = inseminationDate.toDate();
    expect(
      (byId['br_br1_preg']!['dueDate'] as Timestamp).toDate(),
      ins.add(const Duration(days: 30)),
    );
    expect(
      (byId['br_br1_prep']!['dueDate'] as Timestamp).toDate(),
      ins.add(const Duration(days: 107)),
    );
    expect(
      (byId['br_br1_farr']!['dueDate'] as Timestamp).toDate(),
      ins.add(const Duration(days: 114)),
    );

    // Every derived task is autoGenerated, status=open, with a source ref.
    for (final d in snap.docs) {
      expect(d.data()['autoGenerated'], isTrue);
      expect(d.data()['status'], 'open');
      expect(d.data()['source']['collection'], 'breeding_records');
      expect(d.data()['source']['docId'], 'br1');
      expect(d.data()['relatedPigId'], 'sow1');
      expect(d.data()['relatedBreedingId'], 'br1');
      expect(d.data()['relatedAreaId'], 'a1');
    }
  });

  test('idempotent — re-running with same source upserts (no duplicates)',
      () async {
    final f = FakeFirebaseFirestore();
    final tasks = TaskRepository(f);
    final gen = TaskGenerator(f, tasks);
    final ts = Timestamp.fromMillisecondsSinceEpoch(1700000000000);

    final b1 = f.batch();
    gen.addBreedingTasksToBatch(
      batch: b1,
      farmId: 'f1',
      breedingRecordId: 'br1',
      sowId: 's1',
      sowTagId: 'S',
      areaId: 'a',
      inseminationDate: ts,
    );
    await b1.commit();

    final b2 = f.batch();
    gen.addBreedingTasksToBatch(
      batch: b2,
      farmId: 'f1',
      breedingRecordId: 'br1',
      sowId: 's1',
      sowTagId: 'S',
      areaId: 'a',
      inseminationDate: ts,
    );
    await b2.commit();

    final snap =
        await f.collection('farms').doc('f1').collection('tasks').get();
    expect(snap.docs, hasLength(3));
  });

  test('addWithdrawalTaskToBatch writes a single withdrawal_end task',
      () async {
    final f = FakeFirebaseFirestore();
    final gen = TaskGenerator(f, TaskRepository(f));
    final batch = f.batch();
    final due = Timestamp.fromMillisecondsSinceEpoch(1710000000000);

    gen.addWithdrawalTaskToBatch(
      batch: batch,
      farmId: 'f1',
      healthRecordId: 'hr1',
      pigId: 'p1',
      tagId: 'PIG-007',
      areaId: 'a1',
      withdrawalEndDate: due,
    );
    await batch.commit();

    final snap =
        await f.collection('farms').doc('f1').collection('tasks').get();
    expect(snap.docs, hasLength(1));
    final doc = snap.docs.single;
    expect(doc.id, 'hr_hr1_wd');
    expect(doc.data()['type'], 'withdrawal_end');
    expect(doc.data()['relatedPigId'], 'p1');
    expect(doc.data()['source']['collection'], 'health_records');
  });
}
