// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCFtQ3C6EbzkQEJS7e3mV3MimyyjF_bq_I',
    appId: '1:1052795186381:web:ca35c9252d81c7cf144d84',
    messagingSenderId: '1052795186381',
    projectId: 'farm-app-mvp',
    authDomain: 'farm-app-mvp.firebaseapp.com',
    storageBucket: 'farm-app-mvp.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAmiku0HSmXkghMUG1pc2uzA99d3Zcv_SQ',
    appId: '1:1052795186381:android:ba88031ac238fd1a144d84',
    messagingSenderId: '1052795186381',
    projectId: 'farm-app-mvp',
    storageBucket: 'farm-app-mvp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCoCW2ZXyH8zUrDJSOHz5i8xgd-qg3_G14',
    appId: '1:1052795186381:ios:d2974f0a0890ca25144d84',
    messagingSenderId: '1052795186381',
    projectId: 'farm-app-mvp',
    storageBucket: 'farm-app-mvp.firebasestorage.app',
    iosBundleId: 'com.example.farmApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCoCW2ZXyH8zUrDJSOHz5i8xgd-qg3_G14',
    appId: '1:1052795186381:ios:d2974f0a0890ca25144d84',
    messagingSenderId: '1052795186381',
    projectId: 'farm-app-mvp',
    storageBucket: 'farm-app-mvp.firebasestorage.app',
    iosBundleId: 'com.example.farmApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCFtQ3C6EbzkQEJS7e3mV3MimyyjF_bq_I',
    appId: '1:1052795186381:web:d4aff5252b56b8a9144d84',
    messagingSenderId: '1052795186381',
    projectId: 'farm-app-mvp',
    authDomain: 'farm-app-mvp.firebaseapp.com',
    storageBucket: 'farm-app-mvp.firebasestorage.app',
  );
}
