import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:fake_cloud_firestore/fake_cloud_firestore.dart';
import 'package:farm_app/src/features/activity/data/activity_repository.dart';
import 'package:farm_app/src/features/pigs/data/batch_repository.dart';
import 'package:farm_app/src/features/pigs/data/farrowing_repository.dart';
import 'package:flutter_test/flutter_test.dart';

({
  FarrowingRepository repo,
  FakeFirebaseFirestore firestore,
}) newRepo() {
  final f = FakeFirebaseFirestore();
  final activity = ActivityRepository(f);
  final batches = BatchRepository(f, activity);
  return (repo: FarrowingRepository(f, activity, batches), firestore: f);
}

Future<void> _seedBreedingAndTask(
  FakeFirebaseFirestore f, {
  required String farmId,
  required String sowId,
  required String breedingRecordId,
}) async {
  await f
      .collection('farms')
      .doc(farmId)
      .collection('pigs')
      .doc(sowId)
      .collection('breeding_records')
      .doc(breedingRecordId)
      .set({
    'boarId': 'b1',
    'inseminationDate': Timestamp.now(),
    'method': 'natural',
    'confirmed': true,
    'expectedFarrowingDate': Timestamp.now(),
    'status': 'confirmed',
    'createdBy': 'u',
    'createdAt': Timestamp.now(),
  });
  await f
      .collection('farms')
      .doc(farmId)
      .collection('tasks')
      .doc('br_${breedingRecordId}_farr')
      .set({
    'type': 'farrowing_expected',
    'title': 'Farrowing due',
    'dueDate': Timestamp.now(),
    'status': 'open',
    'autoGenerated': true,
    'createdAt': Timestamp.now(),
  });
}

void main() {
  test(
      'logFarrowing writes farrowing record, closes breeding, completes farrowing task, creates litter batch atomically',
      () async {
    final t = newRepo();
    await _seedBreedingAndTask(
      t.firestore,
      farmId: 'f1',
      sowId: 'sow1',
      breedingRecordId: 'br1',
    );

    final id = await t.repo.logFarrowing(
      farmId: 'f1',
      sowId: 'sow1',
      sowTagId: 'SOW-1',
      sowAreaId: 'a1',
      sowPenId: null,
      breedingRecordId: 'br1',
      date: Timestamp.now(),
      liveBorn: 10,
      stillborn: 1,
      mummified: 0,
      avgBirthWeightKg: 1.4,
      createLitterBatch: true,
      notes: null,
      actorUserId: 'u1',
      actorDisplayName: 'Juan',
    );

    // Farrowing record exists with the expected values + litter batch link.
    final farr = await t.firestore
        .collection('farms')
        .doc('f1')
        .collection('pigs')
        .doc('sow1')
        .collection('farrowing_records')
        .doc(id)
        .get();
    expect(farr.exists, isTrue);
    expect(farr.data()!['liveBorn'], 10);
    expect(farr.data()!['stillborn'], 1);
    expect(farr.data()!['mummified'], 0);
    expect(farr.data()!['avgBirthWeightKg'], 1.4);
    expect(farr.data()!['breedingRecordId'], 'br1');
    expect(farr.data()!['litterBatchId'], isNotNull);

    // Breeding record was closed (status='farrowed').
    final br = await t.firestore
        .collection('farms')
        .doc('f1')
        .collection('pigs')
        .doc('sow1')
        .collection('breeding_records')
        .doc('br1')
        .get();
    expect(br.data()!['status'], 'farrowed');

    // Farrowing-expected task was completed.
    final task = await t.firestore
        .collection('farms')
        .doc('f1')
        .collection('tasks')
        .doc('br_br1_farr')
        .get();
    expect(task.data()!['status'], 'completed');
    expect(task.data()!['completedBy'], 'u1');

    // A new litter batch was created with count == liveBorn.
    final batches = await t.firestore
        .collection('farms')
        .doc('f1')
        .collection('batches')
        .get();
    expect(batches.docs, hasLength(1));
    expect(batches.docs.first.data()['type'], 'litter');
    expect(batches.docs.first.data()['count'], 10);
    expect(
      List<String>.from(batches.docs.first.data()['originPigIds']),
      ['sow1'],
    );
    expect(batches.docs.first.data()['currentAreaId'], 'a1');

    // Activity entry was written.
    final activity = await t.firestore
        .collection('farms')
        .doc('f1')
        .collection('activity')
        .get();
    expect(
      activity.docs.where((d) => d.data()['action'] == 'farrowing_logged'),
      hasLength(1),
    );
  });

  test('logFarrowing without createLitterBatch skips batch creation',
      () async {
    final t = newRepo();
    await _seedBreedingAndTask(
      t.firestore,
      farmId: 'f1',
      sowId: 'sow1',
      breedingRecordId: 'br1',
    );

    await t.repo.logFarrowing(
      farmId: 'f1',
      sowId: 'sow1',
      sowTagId: 'SOW-1',
      sowAreaId: 'a1',
      sowPenId: 'p1',
      breedingRecordId: 'br1',
      date: Timestamp.now(),
      liveBorn: 8,
      stillborn: 0,
      mummified: 0,
      avgBirthWeightKg: null,
      createLitterBatch: false,
      notes: 'no batch wanted',
      actorUserId: 'u1',
      actorDisplayName: 'Juan',
    );

    final batches = await t.firestore
        .collection('farms')
        .doc('f1')
        .collection('batches')
        .get();
    expect(batches.docs, isEmpty);

    // Breeding still closed even if no batch was made.
    final br = await t.firestore
        .collection('farms')
        .doc('f1')
        .collection('pigs')
        .doc('sow1')
        .collection('breeding_records')
        .doc('br1')
        .get();
    expect(br.data()!['status'], 'farrowed');
  });

  test('logFarrowing skips batch creation when liveBorn is 0 even if toggled on',
      () async {
    final t = newRepo();
    await _seedBreedingAndTask(
      t.firestore,
      farmId: 'f1',
      sowId: 'sow1',
      breedingRecordId: 'br1',
    );

    await t.repo.logFarrowing(
      farmId: 'f1',
      sowId: 'sow1',
      sowTagId: 'SOW-1',
      sowAreaId: 'a1',
      sowPenId: null,
      breedingRecordId: 'br1',
      date: Timestamp.now(),
      liveBorn: 0,
      stillborn: 5,
      mummified: 1,
      avgBirthWeightKg: null,
      createLitterBatch: true,
      notes: null,
      actorUserId: 'u1',
      actorDisplayName: 'Juan',
    );

    final batches = await t.firestore
        .collection('farms')
        .doc('f1')
        .collection('batches')
        .get();
    expect(batches.docs, isEmpty);
  });
}
