import 'package:cloud_firestore/cloud_firestore.dart';
import '../domain/task.dart';

class TaskRepository {
  TaskRepository(this._firestore);
  final FirebaseFirestore _firestore;

  CollectionReference<Map<String, dynamic>> _col(String farmId) =>
      _firestore.collection('farms').doc(farmId).collection('tasks');

  Future<String> createManualTask({
    required String farmId,
    required String title,
    String? description,
    required Timestamp dueDate,
    String? relatedPigId,
    String? relatedAreaId,
    TaskAssignment? assignedTo,
    required String creatorUserId,
  }) async {
    final ref = _col(farmId).doc();
    await ref.set({
      'type': 'manual',
      'title': title,
      if (description != null) 'description': description,
      'dueDate': dueDate,
      if (relatedPigId != null) 'relatedPigId': relatedPigId,
      if (relatedAreaId != null) 'relatedAreaId': relatedAreaId,
      if (assignedTo != null) 'assignedTo': assignedTo.toMap(),
      'status': 'open',
      'autoGenerated': false,
      'createdAt': FieldValue.serverTimestamp(),
    });
    return ref.id;
  }

  Stream<List<FarmTask>> streamOpenTasks(String farmId) {
    return _col(farmId)
        .where('status', isEqualTo: 'open')
        .orderBy('dueDate')
        .snapshots()
        .map((s) => s.docs
            .map((d) => FarmTask.fromFirestore(d, farmId: farmId))
            .toList());
  }

  Stream<List<FarmTask>> streamTasksAssignedToUser({
    required String farmId,
    required String userId,
  }) {
    return _col(farmId)
        .where('status', isEqualTo: 'open')
        .where('assignedTo.kind', isEqualTo: 'user')
        .where('assignedTo.id', isEqualTo: userId)
        .snapshots()
        .map((s) => s.docs
            .map((d) => FarmTask.fromFirestore(d, farmId: farmId))
            .toList());
  }

  Future<void> completeTask({
    required String farmId,
    required String taskId,
    required String userId,
  }) async {
    await _col(farmId).doc(taskId).update({
      'status': 'completed',
      'completedBy': userId,
      'completedAt': FieldValue.serverTimestamp(),
    });
  }
}
