import 'package:cloud_firestore/cloud_firestore.dart';

enum TaskType {
  pregnancyCheck('pregnancy_check', 'Pregnancy check'),
  farrowingPrep('farrowing_prep', 'Farrowing prep'),
  farrowingExpected('farrowing_expected', 'Farrowing expected'),
  vaccinationDue('vaccination_due', 'Vaccination due'),
  withdrawalEnd('withdrawal_end', 'Withdrawal period ends'),
  manual('manual', 'Manual');

  const TaskType(this.value, this.label);
  final String value;
  final String label;
  static TaskType fromString(String s) => TaskType.values
      .firstWhere((t) => t.value == s, orElse: () => TaskType.manual);
}

enum TaskStatus {
  open('open'),
  completed('completed'),
  skipped('skipped');

  const TaskStatus(this.value);
  final String value;
  static TaskStatus fromString(String s) => TaskStatus.values
      .firstWhere((t) => t.value == s, orElse: () => TaskStatus.open);
}

class TaskAssignment {
  final String kind; // 'user' or 'area'
  final String id;
  const TaskAssignment({required this.kind, required this.id});

  Map<String, dynamic> toMap() => {'kind': kind, 'id': id};

  factory TaskAssignment.fromMap(Map<String, dynamic> m) => TaskAssignment(
        kind: m['kind'] as String? ?? 'user',
        id: m['id'] as String? ?? '',
      );
}

class TaskSource {
  final String collection;
  final String docId;
  const TaskSource({required this.collection, required this.docId});

  Map<String, dynamic> toMap() => {'collection': collection, 'docId': docId};

  factory TaskSource.fromMap(Map<String, dynamic> m) => TaskSource(
        collection: m['collection'] as String? ?? '',
        docId: m['docId'] as String? ?? '',
      );
}

class FarmTask {
  final String id;
  final String farmId;
  final TaskType type;
  final String title;
  final String? description;
  final Timestamp dueDate;
  final String? relatedPigId;
  final String? relatedBreedingId;
  final String? relatedBatchId;
  final String? relatedAreaId;
  final TaskAssignment? assignedTo;
  final TaskStatus status;
  final bool autoGenerated;
  final TaskSource? source;
  final String? completedBy;
  final Timestamp? completedAt;
  final Timestamp createdAt;

  const FarmTask({
    required this.id,
    required this.farmId,
    required this.type,
    required this.title,
    required this.description,
    required this.dueDate,
    required this.relatedPigId,
    required this.relatedBreedingId,
    required this.relatedBatchId,
    required this.relatedAreaId,
    required this.assignedTo,
    required this.status,
    required this.autoGenerated,
    required this.source,
    required this.completedBy,
    required this.completedAt,
    required this.createdAt,
  });

  factory FarmTask.fromFirestore(DocumentSnapshot doc, {required String farmId}) {
    final d = doc.data() as Map<String, dynamic>;
    return FarmTask(
      id: doc.id,
      farmId: farmId,
      type: TaskType.fromString(d['type'] as String? ?? 'manual'),
      title: d['title'] as String? ?? '',
      description: d['description'] as String?,
      dueDate: d['dueDate'] as Timestamp? ?? Timestamp.now(),
      relatedPigId: d['relatedPigId'] as String?,
      relatedBreedingId: d['relatedBreedingId'] as String?,
      relatedBatchId: d['relatedBatchId'] as String?,
      relatedAreaId: d['relatedAreaId'] as String?,
      assignedTo: d['assignedTo'] != null
          ? TaskAssignment.fromMap(d['assignedTo'] as Map<String, dynamic>)
          : null,
      status: TaskStatus.fromString(d['status'] as String? ?? 'open'),
      autoGenerated: d['autoGenerated'] as bool? ?? false,
      source: d['source'] != null
          ? TaskSource.fromMap(d['source'] as Map<String, dynamic>)
          : null,
      completedBy: d['completedBy'] as String?,
      completedAt: d['completedAt'] as Timestamp?,
      createdAt: d['createdAt'] as Timestamp? ?? Timestamp.now(),
    );
  }

  Map<String, dynamic> toMap() => {
        'type': type.value,
        'title': title,
        if (description != null) 'description': description,
        'dueDate': dueDate,
        if (relatedPigId != null) 'relatedPigId': relatedPigId,
        if (relatedBreedingId != null) 'relatedBreedingId': relatedBreedingId,
        if (relatedBatchId != null) 'relatedBatchId': relatedBatchId,
        if (relatedAreaId != null) 'relatedAreaId': relatedAreaId,
        if (assignedTo != null) 'assignedTo': assignedTo!.toMap(),
        'status': status.value,
        'autoGenerated': autoGenerated,
        if (source != null) 'source': source!.toMap(),
        if (completedBy != null) 'completedBy': completedBy,
        if (completedAt != null) 'completedAt': completedAt,
        'createdAt': createdAt,
      };
}
