import 'package:cloud_firestore/cloud_firestore.dart';
import '../data/task_repository.dart';

class TaskGenerator {
  TaskGenerator(this._firestore, this._tasks);
  final FirebaseFirestore _firestore;
  // ignore: unused_field
  final TaskRepository _tasks;

  CollectionReference<Map<String, dynamic>> _tasksCol(String farmId) =>
      _firestore.collection('farms').doc(farmId).collection('tasks');

  /// Idempotent task ID derived from source. Re-runs upsert the same doc IDs
  /// so duplicate breeding writes cannot create duplicate tasks.
  String _taskIdFor(String breedingRecordId, String suffix) =>
      'br_${breedingRecordId}_$suffix';

  void addBreedingTasksToBatch({
    required WriteBatch batch,
    required String farmId,
    required String breedingRecordId,
    required String sowId,
    required String sowTagId,
    String? areaId,
    required Timestamp inseminationDate,
  }) {
    final ins = inseminationDate.toDate();
    final pregCheck = ins.add(const Duration(days: 30));
    final farrPrep = ins.add(const Duration(days: 107));
    final farrExp = ins.add(const Duration(days: 114));

    _writeTask(
      batch,
      farmId,
      _taskIdFor(breedingRecordId, 'preg'),
      type: 'pregnancy_check',
      title: 'Pregnancy check for $sowTagId',
      dueDate: Timestamp.fromDate(pregCheck),
      relatedPigId: sowId,
      relatedBreedingId: breedingRecordId,
      areaId: areaId,
      source: {'collection': 'breeding_records', 'docId': breedingRecordId},
    );
    _writeTask(
      batch,
      farmId,
      _taskIdFor(breedingRecordId, 'prep'),
      type: 'farrowing_prep',
      title: 'Farrowing prep for $sowTagId',
      dueDate: Timestamp.fromDate(farrPrep),
      relatedPigId: sowId,
      relatedBreedingId: breedingRecordId,
      areaId: areaId,
      source: {'collection': 'breeding_records', 'docId': breedingRecordId},
    );
    _writeTask(
      batch,
      farmId,
      _taskIdFor(breedingRecordId, 'farr'),
      type: 'farrowing_expected',
      title: 'Farrowing expected for $sowTagId',
      dueDate: Timestamp.fromDate(farrExp),
      relatedPigId: sowId,
      relatedBreedingId: breedingRecordId,
      areaId: areaId,
      source: {'collection': 'breeding_records', 'docId': breedingRecordId},
    );
  }

  void addWithdrawalTaskToBatch({
    required WriteBatch batch,
    required String farmId,
    required String healthRecordId,
    required String pigId,
    required String tagId,
    String? areaId,
    required Timestamp withdrawalEndDate,
  }) {
    _writeTask(
      batch,
      farmId,
      'hr_${healthRecordId}_wd',
      type: 'withdrawal_end',
      title: 'Withdrawal period ends for $tagId',
      dueDate: withdrawalEndDate,
      relatedPigId: pigId,
      areaId: areaId,
      source: {'collection': 'health_records', 'docId': healthRecordId},
    );
  }

  void _writeTask(
    WriteBatch batch,
    String farmId,
    String taskId, {
    required String type,
    required String title,
    required Timestamp dueDate,
    String? relatedPigId,
    String? relatedBreedingId,
    String? areaId,
    Map<String, String>? source,
  }) {
    batch.set(_tasksCol(farmId).doc(taskId), {
      'type': type,
      'title': title,
      'dueDate': dueDate,
      if (relatedPigId != null) 'relatedPigId': relatedPigId,
      if (relatedBreedingId != null) 'relatedBreedingId': relatedBreedingId,
      if (areaId != null) 'relatedAreaId': areaId,
      'status': 'open',
      'autoGenerated': true,
      if (source != null) 'source': source,
      'createdAt': FieldValue.serverTimestamp(),
    });
  }
}
